title: narusas's blog
description: SW,IT에 대해 끄적입니다
keep_files:
  - images
exclude:
  - LICENSE.adoc
  - README.adoc
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - vendor
asciidoc: {}
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    imagesdir: /images
    idseparator: _
    source-highlighter: coderay
    icons: font
plugins:
  - jekyll-asciidoc
  - asciidoctor-diagram
  - jekyll-diagrams
